;*
================================================================================

    extracted.hsc, file 1 of 1

    generated by Invader 0.54.2.r4101

================================================================================
*;

(global boolean in_combat 0)


(script continuous anti-cheat
    (if
        (= cheat_deathless_player 1)
        (begin
            (sound_impulse_start levels\test\nuts\sounds\no none 1.000000)
            (sleep 90)
            	(unit_kill (player0))
            	(unit_kill (player1)) ;; co-op ""fix"" lol
            (set cheat_deathless_player 0)
        )
    )
    (if
        (= cheat_omnipotent 1)
        (begin
            (sound_impulse_start levels\test\nuts\sounds\no none 1.000000)
            (sleep 90)
            	(unit_kill (player0))
            	(unit_kill (player1))
            (set cheat_omnipotent 0)
        )
    )
    (if
        (= cheat_medusa 1)
        (begin
            (sound_impulse_start levels\test\nuts\sounds\no none 1.000000)
            (sleep 90)
            	(unit_kill (player0))
            	(unit_kill (player1))
            (set cheat_medusa 0)
        )
    )
    (if
        (= cheat_super_jump 1)
        (begin
            (sound_impulse_start levels\test\nuts\sounds\no none 1.000000)
            (sleep 90)
            	(unit_kill (player0))
            	(unit_kill (player1))
            (set cheat_super_jump 0)
        )
    )
    (if
        (= cheat_infinite_ammo 1)
        (begin
            (sound_impulse_start levels\test\nuts\sounds\no none 1.000000)
            (sleep 90)
            	(unit_kill (player0))
            	(unit_kill (player1))
            (set cheat_infinite_ammo 0)
        )
    )
    (if
        (= cheat_infinite_ammo 1)
        (begin
            (sound_impulse_start levels\test\nuts\sounds\no none 1.000000)
            (sleep 90)
            	(unit_kill (player0))
            	(unit_kill (player1))
            (set cheat_infinite_ammo 0)
        )
    )
    (if
        (= cheat_bump_possession 1)
        (begin
            (sound_impulse_start levels\test\nuts\sounds\no none 1.000000)
            (sleep 90)
            	(unit_kill (player0))
            	(unit_kill (player1))
            (set cheat_bump_possession 0)
        )
    )
    (if
        (= cheat_jetpack 1)
        (begin
            (sound_impulse_start levels\test\nuts\sounds\no none 1.000000)
            (sleep 90)
            	(unit_kill (player0))
            	(unit_kill (player1))
            (set cheat_jetpack 0)
        )
    )
)

;; this script name had some naughty words in it so i renamed it :)
(script startup "main"
    (cinematic_set_title welcome)
    (sleep 120)
    (object_create control_round_1)
    (activate_team_nav_point_object default player control_round_1 0.500000)
    (sleep_until
        (= (device_get_position control_round_1) 1.000000)
    )
    (cinematic_set_title round_1)
    (deactivate_team_nav_point_object player control_round_1)
    (sound_impulse_start levels\test\nuts\sounds\round_countdown none 1.000000)
    (sleep 100)
    (ai_place round_fake)
    (ai_retreat round_fake)
    (sleep 20)
    (sleep_until
        (= (ai_living_count round_fake) 0)
    )
    (sound_impulse_start levels\test\nuts\sounds\begin_round_1 none 1.000000)
    (sleep 275)
    (ai_place round_1)
    (set in_combat 1)
    (sleep_until
        (< (ai_living_fraction round_1) 0.500000)
    )
    (sound_impulse_start levels\test\nuts\sounds\half_round_complete none 1.000000)
    (sleep 90)
    (sleep_until
        (= (ai_living_count round_1) 0)
    )
    (set in_combat 0)
    (sound_impulse_start levels\test\nuts\sounds\end_round_1 none 1.000000)
    (object_create control_round_2)
    (activate_team_nav_point_object default player control_round_2 0.500000)
    (sleep_until
        (= (device_get_position control_round_2) 1.000000)
    )
    (cinematic_set_title round_2)
    (deactivate_team_nav_point_object player control_round_2)
    (sound_impulse_start levels\test\nuts\sounds\begin_round_2 none 1.000000)
    (sleep 120)
    (sleep 213)
    (ai_place round_2)
    (set in_combat 1)
    (sleep_until
        (< (ai_living_fraction round_2) 0.500000)
    )
    (sound_impulse_start levels\test\nuts\sounds\half_round_complete none 1.000000)
    (sleep 90)
    (sleep_until
        (= (ai_living_count round_2) 0)
    )
    (set in_combat 0)
    (sound_impulse_start levels\test\nuts\sounds\end_round_2 none 1.000000)
    (object_create control_round_3)
    (activate_team_nav_point_object default player control_round_3 0.500000)
    (sleep_until
        (= (device_get_position control_round_3) 1.000000)
    )
    (cinematic_set_title round_3)
    (deactivate_team_nav_point_object player control_round_3)
    (sound_impulse_start levels\test\nuts\sounds\begin_round_3 none 1.000000)
    (sleep 156)
    (ai_place round_3)
    (set in_combat 1)
    (sleep_until
        (< (ai_living_fraction round_3) 0.500000)
    )
    (sound_impulse_start levels\test\nuts\sounds\half_round_complete none 1.000000)
    (sleep 90)
    (sleep_until
        (= (ai_living_count round_3) 0)
    )
    (set in_combat 0)
    (sound_impulse_start levels\test\nuts\sounds\end_round_3 none 1.000000)
    (object_create control_round_4)
    (activate_team_nav_point_object default player control_round_4 0.500000)
    (sleep_until
        (= (device_get_position control_round_4) 1.000000)
    )
    (cinematic_set_title round_4)
    (deactivate_team_nav_point_object player control_round_4)
    (sound_impulse_start levels\test\nuts\sounds\begin_round_4 none 1.000000)
    (sleep 60)
    (ai_place round_4)
    (set in_combat 1)
    (sleep 60)
    (sleep_until
        (< (ai_living_fraction round_4) 0.500000)
    )
    (sound_impulse_start levels\test\nuts\sounds\half_round_complete none 1.000000)
    (sleep 90)
    (sleep_until
        (< (ai_living_count round_4) 10)
    )
    (set in_combat 0)
    (sound_impulse_start levels\test\nuts\sounds\end_round_4 none 1.000000)
    (object_create control_round_5)
    (activate_team_nav_point_object default player control_round_5 0.500000)
    (sleep_until
        (= (device_get_position control_round_5) 1.000000)
    )
    (cinematic_set_title round_5)
    (deactivate_team_nav_point_object player control_round_5)
    (sound_impulse_start levels\test\nuts\sounds\begin_round_5 none 1.000000)
    (sleep 150)
    (ai_place round_5)
    (set in_combat 1)
    (sleep_until
        (< (ai_living_fraction round_5) 0.500000)
    )
    (sound_impulse_start levels\test\nuts\sounds\half_round_complete none 1.000000)
    (sleep 90)
    (sleep_until
        (= (ai_living_count round_5) 0)
    )
    (set in_combat 0)
    (sound_impulse_start levels\test\nuts\sounds\end_round_5 none 1.000000)
    (cinematic_set_title winner)
    (sleep 120)
    (sleep 780)
    (cinematic_start)
    (object_create crusher_hog)
    (camera_control 1)
    (camera_set squash_camera 0)
    (object_teleport
        (player0)
        squash_flag
    )
    (object_teleport
        (player1)
        squash_flag_c
    )
    (sleep 300)
    (camera_control 0)
    (effect_new "vehicles\fighterbomber\nuke\huge explosion" kaboom)
    (sleep 10)
	(unit_kill (player0))
	(unit_kill (player1)) ;; coop """bugfix"""

	(sleep 150)
	(game_revert) ;; unwinnable map, aren't i a stinker!
)

;; this was broken in original. fixed
(script startup "ooo you died loloolololo"
    (sleep_until
        (and (< (unit_get_health (player0)) 0.000000) (< (unit_get_health (player1)) 0.000000))
        1
    )
	(sound_impulse_start levels\test\nuts\sounds\fuck none 1.000000)
)

;; new script to restore the infraction cut content... thing?
(script startup infraction_start
	(sleep_until (> (device_get_position control_infraction) 0) 5)
        (sound_impulse_start levels\test\nuts\sounds\roll none 1.000000)
	(wake infraction)
)

(script dormant infraction
    (ai_place backseat_moderation/kornman00)
    (ai_place backseat_moderation/p0lar_bear)
    (ai_place backseat_moderation/jcap)
    (ai_place "backseat_moderation/the ghost")
    ;;(sv_say "teh easterz eggz ayayayayayaya")
)


(script continuous "infraction sounds"
    (sleep_until
        (> (ai_living_count backseat_moderation) 1)
    )
    (if
        (= in_combat 1)
        (begin
            (object_create searching)
            (object_destroy alert)
        )
        (begin
            (object_create alert)
            (object_destroy searching)
        )
    )
)


(script continuous "infraction byebye"
    (sleep_until
        (< (ai_living_count backseat_moderation) 1)
    )
    (object_destroy alert)
    (object_destroy searching)
)

