;*
================================================================================

    extracted.hsc, file 1 of 1

    generated by invader 0.54.2.r4101

================================================================================
*;

(script startup teleporters
    (object_set_scale tele_1 2.000000 1)
    (object_set_scale tele_2 2.000000 1)
)


(script startup "sleep till unban"
    (sleep 3000)
    (sv_say "i like the teal")
)

